### ISSUE TITLE
can you give a trained model for demo？

### ISSUE THREAD

**Issue by l2009312042** [noahchalifour/rnnt-speech-recognition#1]
it is a good job for rnn-t asr，thank you for share your work . can you give a trained model for  demo test？ thanks

**Comment by noahchalifour** [comment]
Yeah, I will be training and publishing a large pre-trained model soon

**Comment by kjwill555** [comment]
@noahchalifour any update on the pre-trained model?

Also, how long does it to train a model using the default parameters?

**Comment by noahchalifour** [comment]
@kjwill555 Because the data is so large I am having to train a model with a batch size of just 2 on a Paperspace VM with a Quadro P4000 GPU. With all other parameters the same it takes about 2 hours to train on a single batch. I am working on optimizing the training process, I also may publish a much smaller pre-trained model as well

**Comment by JudeAshly** [comment]
We are waiting for a trained model : D

**Comment by biemster** [comment]
Have you considered using the trained models from the various Google apps that use this, like GBoard or Recorder? I've been trying that here: https://hackaday.io/project/164399-android-offline-speech-recognition-natively-on-pc
With some great help we got the endpointer giving nice results, but the inputs to the encoder and decoder, and the text output still need some more work/help.

**Comment by Brocolli765** [comment]
Hi guys, it would be nice if anyone could upload the trained model

**Comment by noahchalifour** [comment]
I am still working on training the model, I ran into some issues but hopefully I will be able to upload a decent model soon

**Comment by noahchalifour** [comment]
Due to financial constraints (I only have 11gb of VRAM) It would take a long time for me to train a decent model. I have just updated the code which should make training much faster and more efficient. If anyone trains a good model, please send it to me (chalifournoah@gmail.com) and I will add it to the readme and give you credit. Thanks!

**Comment by PeiyanFlying** [comment]
Excuse me, but I have another question. When I train the model, I always run into "out of memory". Just like this:

RuntimeError: CUDA out of memory. Tried to allocate 8.05 GiB (GPU 0; 23.62 GiB total capacity; 18.02 GiB already allocated; 2.84 GiB free; 19.59 GiB reserved in total by PyTorch)

I use one GPU to train, the memory size is 23.6GiB. So how could you succeed running model only on one GPU？
Many thanks!

The dataset is LibriSpeech.
